package ru.maxmorev.eshop.customer.order.api.entities;

public interface Constants {

    String ID_GENERATOR_ORDER = "ID_GENERATOR_ORDER";
    String ID_GENERATOR_ORDER_SEQUENCE_NAME = "RES_SEQUENCE_ORDER";

    String ID_GENERATOR_SHOPPING_CART = "ID_GENERATOR_SHOPPING_CART";
    String ID_GENERATOR_SHOPPING_CART_SEQUENCE_NAME = "RES_SEQUENCE_SHOPPING_CART";

    String ID_GENERATOR_SHOPPING_CART_SET = "ID_GENERATOR_SHOPPING_CART_SET";
    String ID_GENERATOR_SHOPPING_CART_SET_SEQUENCE_NAME = "RES_SEQUENCE_SHOPPING_CART_SET";


}
